/* config-kwindowsystem.h. Generated by cmake from config-kwindowsystem.h.cmake */

/* Define to 1 if you have the Xlib */
#cmakedefine01 KWINDOWSYSTEM_HAVE_X11

/* Define to 1 if you have the Xfixes library */
#cmakedefine01 KWINDOWSYSTEM_HAVE_XFIXES

/* Define to 1 if you have the Xrender library */
#cmakedefine01 KWINDOWSYSTEM_HAVE_XRENDER

