/* config-kwindowsystem.h. Generated by cmake from config-kwindowsystem.h.cmake */

/* Define to 1 if you have the Xlib */
#cmakedefine01 KWINDOWSYSTEM_HAVE_X11

/* Define to 1 if you have the Xfixes library */
#cmakedefine01 KWINDOWSYSTEM_HAVE_XFIXES

/* Define to 1 if you have the Xrender library */
#cmakedefine01 KWINDOWSYSTEM_HAVE_XRENDER

/* Path to xcb plugin */
#define XCB_PLUGIN_PATH "${CMAKE_INSTALL_PREFIX}/${PLUGIN_INSTALL_DIR}/org.kde.kwindowsystem.platforms/KF5WindowSystemX11Plugin.so"
