/* config-kwindowsystem.h. Generated by cmake from config-kwindowsystem.h.cmake */

/* Define to 1 if you have the Xlib */
#cmakedefine01 KWINDOWSYSTEM_HAVE_X11

/* Define to 1 if you have the Xfixes library */
#cmakedefine01 KWINDOWSYSTEM_HAVE_XFIXES

/* Path to xcb plugin */
#define XCB_PLUGIN_PATH "${KDE_INSTALL_FULL_PLUGINDIR}/kf5/kwindowsystem/KF5WindowSystemX11Plugin.so"
